version: '3.8'

services:
  token-calculator-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - ADMIN_API_KEY=change-me-in-production
      - CORS_ORIGINS=*
      - LOG_LEVEL=INFO
    volumes:
      - ./app/pricing.json:/app/app/pricing.json:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthz/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  # Optional: Add a reverse proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - token-calculator-api
    restart: unless-stopped
